# Generated by Django 3.2.7 on 2021-09-16 13:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
